on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  autoindex:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: arbetsmiljo/autoindex@v37
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          year: ${{ github.event.repository.name }}
